# -*- coding: utf-8 -*-
"""HealthifyAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OebHmU61tU6DMoSuCs9s_w7sH7bKIFrT

## **Healthify AI MLModel**
"""

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import difflib
import warnings

warnings.filterwarnings("ignore")

def normalize(sym):
    return sym.strip().lower().replace(" ", "_")

workout = pd.read_csv("/content/gym dataset.csv")
precaution = pd.read_csv("/content/symptom_precaution.csv")
description = pd.read_csv("/content/symptom_Description.csv")
severity = pd.read_csv("/content/Symptom-severity.csv")
dataset = pd.read_csv("/content/dataset.csv")

symptom_cols = [col for col in dataset.columns if "Symptom_" in col]

dataset["Symptoms"] = dataset[symptom_cols].apply(
    lambda row: [normalize(s) for s in row.dropna().values], axis=1
)

mlb = MultiLabelBinarizer()
X = mlb.fit_transform(dataset["Symptoms"])
y = dataset["Disease"]

known_symptoms = set(mlb.classes_)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

accuracy = accuracy_score(y_test, clf.predict(X_test))
print(f"\n Model Accuracy: {accuracy * 100:.2f}%")

severity_dict = {
    normalize(sym): wt
    for sym, wt in zip(severity["Symptom"], severity["weight"])
}

def match_symptom(sym):
    matches = difflib.get_close_matches(sym, known_symptoms, n=1, cutoff=0.6)
    return matches[0] if matches else None

def predict_disease(user_symptoms):
    user_input = mlb.transform([user_symptoms])
    pred = clf.predict(user_input)[0]

    risk_score = sum(severity_dict.get(sym, 1) for sym in user_symptoms)

    try:
        desc = description.loc[description["Disease"] == pred, "Description"].values[0]
    except:
        desc = "No description available."

    try:
        prec = precaution.loc[
            precaution["Disease"] == pred,
            ["Precaution_1", "Precaution_2", "Precaution_3"]
        ].values[0]
        prec_str = ", ".join([p for p in prec if pd.notnull(p)])
    except:
        prec_str = "No specific precautions found."

    return pred, risk_score, desc, prec_str

def get_fitness_plan(age, gender, height_cm, weight_kg, goal, hypertension):

    sex = "Male" if gender.strip().lower() in ["male", "m"] else "Female"
    height_m = height_cm / 100
    bmi = weight_kg / (height_m ** 2)
    hyper_str = "Yes" if hypertension.strip().lower() == "yes" else "No"

    goal_map = {
        "lose weight": "Weight Loss",
        "gain muscle": "Weight Gain",
        "stay fit": "Weight Gain" # Default, adjusted by BMI below
    }

    user_goal = goal.strip().lower()
    if user_goal == "stay fit":
        target_goal = "Weight Loss" if bmi >= 25 else "Weight Gain"
    else:
        target_goal = goal_map.get(user_goal, "Weight Gain")


    df_filtered = workout[
        (workout['Sex'] == sex) &
        (workout['Hypertension'] == hyper_str) &
        (workout['Fitness Goal'] == target_goal)
    ].copy()

    if df_filtered.empty:
        df_filtered = workout[
            (workout['Sex'] == sex) &
            (workout['Fitness Goal'] == target_goal)
        ].copy()

    if df_filtered.empty:
        df_filtered = workout[workout['Fitness Goal'] == target_goal].copy()

    df_filtered['dist'] = (
        ((df_filtered['Age'] - age) / 100) ** 2 +
        ((df_filtered['BMI'] - bmi) / 50) ** 2
    )

    best_match = df_filtered.loc[df_filtered['dist'].idxmin()]

    return best_match['Diet'], best_match['Exercises'], best_match['Recommendation']

print("\n=== User Details ===")

name = input("Name: ")
try:
    age = int(input("Age: "))
    height_cm = float(input("Height (cm): "))
    weight_kg = float(input("Weight (kg): "))
except ValueError:
    print(" Invalid numeric input. Using defaults (Age: 25, H: 170cm, W: 70kg).")
    age, height_cm, weight_kg = 25, 170.0, 70.0

gender = input("Gender (Male/Female): ")
fitness_goal = input("Fitness Goal (Lose Weight / Gain Muscle / Stay Fit): ")
hypertension = input("Do you have hypertension? (yes/no): ").strip().lower()

bmi = round(weight_kg / ((height_cm / 100) ** 2), 2)

print("\n=== Disease Risk Prediction ===")
common_symptoms = ["fever", "headache", "fatigue", "body pain", "cough", "nausea", "diarrhea"]
user_symptoms = []

for sym in common_symptoms:
    ans = input(f"Do you have {sym}? (yes/no): ").strip().lower()
    if ans == "yes":
        user_symptoms.append(normalize(sym))

other = input("\nAny other symptoms?: ").strip()
if other:
    for s in other.split(","):
        s_norm = normalize(s)
        if s_norm in known_symptoms:
            user_symptoms.append(s_norm)
        else:
            match = match_symptom(s_norm)
            if match:
                print(f"Using closest match: {match}")
                user_symptoms.append(match)

if not user_symptoms:
    print(" No valid symptoms entered. Exiting...")
    exit()

pred, score, desc, prec = predict_disease(user_symptoms)

diet_plan, workout_plan, fit_rec = get_fitness_plan(age, gender, height_cm, weight_kg, fitness_goal, hypertension)

print("\n" + "="*50)
print(f"      HEALTH & WELLNESS REPORT       ")
print("="*50)

print(f"\n PATIENT PROFILE")
print(f"Name         : {name}")
print(f"Age          : {age}")
print(f"Gender       : {gender}")
print(f"BMI          : {bmi} kg/m²")
print(f"Hypertension : {hypertension.capitalize()}")
print(f"Fitness Goal : {fitness_goal}")

print("-" * 50)
print(f" DISEASE DIAGNOSIS")
print(f"Predicted Disease : {pred}")
print(f"Risk Score        : {score}")
print(f"Description       : {desc}")
print(f"Medical Precautions: {prec}")

print("-" * 50)
print(f" CUSTOMIZED DIET PLAN")
print(f"Plan : {diet_plan}")

print("-" * 50)
print(f" WORKOUT ROUTINE")
print(f"Exercises : {workout_plan}")

print("-" * 50)
print(f" WELLNESS RECOMMENDATION")
print(f"Advice : {fit_rec}")

print("="*50)

